[package]
name = "vectro_cli"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
vectro_plus = { path = "../vectro_plus" }
anyhow = "1.0"
serde_json = "1.0"
csv = "1.2"
indicatif = "0.17"
bincode = { workspace = true }
crossbeam-channel = "0.5"
num_cpus = "1.17"

[dev-dependencies]
tempfile = "3.6"
